#!/bin/sh

set -e

yellow=$(tput setaf 3)
normal=$(tput sgr0)

case "$1" in
    configure)
        if [ "x"$2 != "x" ]; then
            # we are doing an upgrade
            exit 0
        fi
        USERNAME='selenium'
	if [ -x "$(command -v adduser)" ]; then
		adduser --system $USERNAME --home /var/lib/hornetq --shell /bin/sh > /dev/null || true
  	else
		echo >&2 "not adding $USERNAME system account because adduser command was not found"
	fi
        systemctl daemon-reload
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
